=== Peterror/PKCK-2018/countries.dtd
<!ELEMENT dokument (opis,kraje,regiony,grupy-etniczne,wydarzenia)>
<!ELEMENT opis (autorzy,streszczenie)>
<!ELEMENT autorzy (autor+)>
<!ELEMENT streszczenie ANY>
<!ELEMENT u (#PCDATA)>

<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor index CDATA #REQUIRED>

<!ELEMENT grupy-etniczne (grupa-etniczna*)>
<!ELEMENT grupa-etniczna EMPTY>
<!ATTLIST grupa-etniczna id ID #IMPLIED>
<!ATTLIST grupa-etniczna idref IDREF #IMPLIED
                        wartość CDATA #IMPLIED
                        jednostka CDATA #IMPLIED>

<!ELEMENT regiony (region-główny+)>
<!ELEMENT region-główny EMPTY>
<!ATTLIST region-główny id ID #REQUIRED>

<!ELEMENT kraje (kraj+)>
<!ELEMENT kraj (nazwa,stolica,grupy-etniczne,strefy-czasowe,ważne-wydarzenia?,populacja,PKB,waluta,region)>

<!ELEMENT stolica (nazwa,współrzędne)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT współrzędne (wysokość,szerokość)>
<!ELEMENT szerokość (#PCDATA)>
<!ELEMENT wysokość (#PCDATA)>

<!ATTLIST szerokość typ (W|E) #REQUIRED>
<!ATTLIST wysokość typ (N|S) #REQUIRED>

<!ELEMENT populacja (#PCDATA)>
<!ATTLIST populacja jednostka (osoba|tyś|mln|mld) "osoba">

<!ELEMENT PKB (#PCDATA)>
<!ATTLIST PKB waluta CDATA "USD"
            jednostka (mln|mld|tyś) "mld">

<!ELEMENT strefy-czasowe (strefa-czasowa+)>
<!ELEMENT strefa-czasowa EMPTY>
<!ATTLIST strefa-czasowa wartość CDATA #REQUIRED
                        znak (p|m) #REQUIRED>

<!ELEMENT waluta (#PCDATA)>

<!ELEMENT ważne-wydarzenia (ważne-wydarzenie*)>
<!ELEMENT ważne-wydarzenie EMPTY>
<!ATTLIST ważne-wydarzenie id IDREF #REQUIRED>

<!ELEMENT region EMPTY>
<!ATTLIST region idref IDREF #REQUIRED>

<!ELEMENT wydarzenia (wydarzenie*)>
<!ELEMENT wydarzenie (nazwa, data)>
<!ELEMENT data EMPTY>
<!ATTLIST wydarzenie id ID #REQUIRED>
<!ATTLIST data dzień CDATA #REQUIRED
                miesiąc (Styczeń|Luty|Marzec|Kwiecień|Maj|Czerwiec|Lipiec|Sierpień|Wrzesień|Październik|Listopad|Grudzień) #REQUIRED
                rok CDATA #REQUIRED>

=== Peterror/PKCK-2018/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE dokument SYSTEM "countries.dtd">

<dokument>
  <opis>
    <autorzy>
      <autor index="204037">Piotr Zieliński</autor>
      <autor index="203967">Łukasz Pierścieniewski</autor>
    </autorzy>
    <streszczenie>
      Dokument ten zawiera informacje na temat wybranych krajów świata. Dla każdego z zawartych krajów umieszczone
      zostały informacje o: <u>stolicy</u> i jej współrzędnych geograficznych, podziału na <u>grupy etniczne</u> i 
      <u>strefy czasowe</u>. Dodatkowo informacje o <u>populacji</u>, <u>PKB</u>, <u>walucie</u> oraz <u>regionie</u>
      zostały przypisane do każdego państwa. Przechowywana jest też informacja na temat <u>ważnych wydarzeń</u> 
      oraz krajów których one dotyczyły
    </streszczenie>
  </opis>

  <!--Tutaj lista krajów -->
  <kraje>
    <kraj>
      <nazwa>Polska</nazwa>
      <stolica>
        <nazwa>Warszawa</nazwa>
        <współrzędne>
          <wysokość typ="N">52.13</wysokość>
          <szerokość typ="E">21.02</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Polacy" wartość="94.6" />
        <grupa-etniczna idref="Niemcy" wartość="0.28" />
        <grupa-etniczna idref="Ukraincy" wartość="0.12" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +1</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="chrzestPolski" />
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>38422346</populacja>
      <PKB>482,9 mld</PKB>
      <waluta>PLN</waluta>
      <region idref="Europa" />
    </kraj>

    <kraj>
      <nazwa>Niemcy</nazwa>
      <stolica>
        <nazwa>Berlin</nazwa>
        <współrzędne>
          <wysokość typ="N">52.31</wysokość>
          <szerokość typ="E">12.24</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Niemcy" wartość="80.8" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +1</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>82349400</populacja>
      <PKB>3466,6 mld</PKB>
      <waluta>EUR</waluta>
      <region idref="Europa" />
    </kraj>

	  <kraj>
      <nazwa>Stany Zjednoczone</nazwa>
      <stolica>
        <nazwa>Waszyngton</nazwa>
        <współrzędne>
          <wysokość typ="N">38.53</wysokość>
          <szerokość typ="W">77.02</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Biali" wartość="77.1" />
        <grupa-etniczna idref="Czarni" wartość="13.3" />
        <grupa-etniczna idref="Azjaci" wartość="5.6" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC -4</strefa-czasowa>
        <strefa-czasowa>UTC -6</strefa-czasowa>
        <strefa-czasowa>UTC -7</strefa-czasowa>
        <strefa-czasowa>UTC -8</strefa-czasowa> 
        <strefa-czasowa>UTC -9</strefa-czasowa> 
        <strefa-czasowa>UTC -10</strefa-czasowa>
        <strefa-czasowa>UTC -11</strefa-czasowa>
        <strefa-czasowa>UTC -12</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
        <ważne-wydarzenie id="deklaracjaNiepodległości" />
      </ważne-wydarzenia>
      <populacja>326079000</populacja>
      <PKB>18036,6 mld</PKB>
      <waluta>USD</waluta>
      <region idref="A.Północna" />
    </kraj>
    <kraj>
      <nazwa>Republika Czeska</nazwa>
      <stolica>
        <nazwa>Praga</nazwa>
        <współrzędne>
          <wysokość typ="N">50.05</wysokość>
          <szerokość typ="E">14.25</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Czesi" wartość="64" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +1</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>10541466</populacja>
      <PKB>193,5 mld</PKB>
      <waluta>CZK</waluta>
      <region idref="Europa" />
    </kraj>
	  <kraj>
      <nazwa>Rosja</nazwa>
      <stolica>
        <nazwa>Moskwa</nazwa>
        <współrzędne>
          <wysokość typ="N">55.45</wysokość>
          <szerokość typ="E">37.37</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Rosjanie" wartość="81" />
        <grupa-etniczna idref="Tatarzy" wartość="3.7" />
        <grupa-etniczna idref="Ukraincy" wartość="1.4" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +2</strefa-czasowa>
        <strefa-czasowa>UTC +3</strefa-czasowa>
        <strefa-czasowa>UTC +4</strefa-czasowa>
        <strefa-czasowa>UTC +5</strefa-czasowa>
        <strefa-czasowa>UTC +6</strefa-czasowa>
        <strefa-czasowa>UTC +7</strefa-czasowa>
        <strefa-czasowa>UTC +8</strefa-czasowa>
        <strefa-czasowa>UTC +9</strefa-czasowa>
        <strefa-czasowa>UTC +10</strefa-czasowa>    
        <strefa-czasowa>UTC +11</strefa-czasowa>
        <strefa-czasowa>UTC +12</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>146877088</populacja>
      <PKB>1522,9 mld</PKB>
      <waluta>RUB</waluta>
      <region idref="Azja" />
    </kraj>
    <kraj>
      <nazwa>Chiny</nazwa>
      <stolica>
        <nazwa>Pekin</nazwa>
        <współrzędne>
          <wysokość typ="N">39.55</wysokość>
          <szerokość typ="E">116.23</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Han" wartość="91.51" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +8</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>1379302771</populacja>
      <PKB>13118,7 mld</PKB>
      <waluta>CNY</waluta>
      <region idref="Azja" />
    </kraj>
    <kraj>
      <nazwa>Zjednoczone Emiraty Arabskie</nazwa>
      <stolica>
        <nazwa>Abu Zabi</nazwa>
        <współrzędne>
          <wysokość typ="N">24.27</wysokość>
          <szerokość typ="E">54.23</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Hindusi" wartość="50" />
        <grupa-etniczna idref="Pakistańczycy" wartość="12.53" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +4</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
      </ważne-wydarzenia>
      <populacja>5927482</populacja>
      <PKB>345,4 mld</PKB>
      <waluta>AED</waluta>
      <region idref="Azja" />
    </kraj>
    <kraj>
      <nazwa>Egipt</nazwa>
      <stolica>
        <nazwa>Kair</nazwa>
        <współrzędne>
          <wysokość typ="N">30.03</wysokość>
          <szerokość typ="E">31.14</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Arabowie" wartość="90" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +2</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
      </ważne-wydarzenia>
      <populacja>97041072</populacja>
      <PKB>330,8 mld</PKB>
      <waluta>EGP</waluta>
      <region idref="Afryka" />
    </kraj>
    <kraj>
      <nazwa>Południowa Afryka</nazwa>
      <stolica>
        <nazwa>Pretoria</nazwa>
        <współrzędne>
          <wysokość typ="S">25.43</wysokość>
          <szerokość typ="E">28.14</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Czarni" wartość="80.2" />
        <grupa-etniczna idref="Biali" wartość="8.4" />
        <grupa-etniczna idref="Azjaci" wartość="2.5" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +2</strefa-czasowa>
      </strefy-czasowe>
      <populacja>54841552</populacja>
      <PKB>384,3 mld</PKB>
      <waluta>ZAR</waluta>
      <region idref="Afryka" />
    </kraj>
    <kraj>
      <nazwa>Francja</nazwa>
      <stolica>
        <nazwa>Paryż</nazwa>
        <współrzędne>
          <wysokość typ="N">48.52</wysokość>
          <szerokość typ="E">2.21</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Biali" wartość="89.4" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC +1</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
        <ważne-wydarzenie id="drugaWojna" />
      </ważne-wydarzenia>
      <populacja>67158000</populacja>
      <PKB>2421,5 mld</PKB>
      <waluta>EUR</waluta>
      <region idref="Europa" />
    </kraj>
    <kraj>
      <nazwa>Kanada</nazwa>
      <stolica>
        <nazwa>Ottawa</nazwa>
        <współrzędne>
          <wysokość typ="N">45.25</wysokość>
          <szerokość typ="W">75.42</szerokość>
        </współrzędne>
      </stolica>
      <grupy-etniczne>
        <grupa-etniczna idref="Europejczycy" wartość="74.3" />
        <grupa-etniczna idref="Azjaci" wartość="14.5" />
      </grupy-etniczne>
      <strefy-czasowe>
        <strefa-czasowa>UTC -3</strefa-czasowa>
        <strefa-czasowa>UTC -4</strefa-czasowa>
        <strefa-czasowa>UTC -5</strefa-czasowa>
        <strefa-czasowa>UTC -6</strefa-czasowa>
        <strefa-czasowa>UTC -7</strefa-czasowa>
        <strefa-czasowa>UTC -8</strefa-czasowa>
      </strefy-czasowe>
      <ważne-wydarzenia>
      </ważne-wydarzenia>
      <populacja>36708083</populacja>
      <PKB>1788,7 mld</PKB>
      <waluta>CAD</waluta>
      <region idref="A.Północna" />
    </kraj>
    <kraj>
      <nazwa>Meksyk</nazwa>
      <stolica>
        <nazwa>Meksyk</nazwa>
        <współrzędne>
          <wysokość typ="N">19.25</wysokość>
